development:
 bucket: autofrio
 access_key_id: AKIAJY3EWLP2NDD7Y7TQ
 secret_access_key: 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
test:
 bucket: autofrio
 access_key_id: AKIAJY3EWLP2NDD7Y7TQ
 secret_access_key: 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
production:
 bucket: autofrio
 access_key_id: AKIAJY3EWLP2NDD7Y7TQ
 secret_access_key: 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